AWSTemplateFormatVersion: 2010-09-09
Description: "test"
Parameters:
  NotificationEmailAddressForCloudWatchAlarms:
    Type: String
    Description: Email address that will be subscribed to the SNS topic for CloudWatch
      alarms and rules (a subscription confirmation email will be sent).
    AllowedPattern: ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: Must be a valid email address!
Resources:
  MasterConfigRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - !Sub
        - arn:${Partition}:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - Partition:
            !If
            - GovCloudCondition
            - aws-us-gov
            - aws
      - !Sub
        - arn:${Partition}:iam::aws:policy/AWSCloudTrailReadOnlyAccess
        - Partition:
            !If
            - GovCloudCondition
            - aws-us-gov
            - aws
      - !Sub
        - arn:${Partition}:iam::aws:policy/IAMReadOnlyAccess
        - Partition:
            !If
            - GovCloudCondition
            - aws-us-gov
            - aws
      - !Sub
        - arn:${Partition}:iam::aws:policy/service-role/AWSConfigRulesExecutionRole
        - Partition:
            !If
            - GovCloudCondition
            - aws-us-gov
            - aws
      - !Sub
        - arn:${Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Partition:
            !If
            - GovCloudCondition
            - aws-us-gov
            - aws
      Policies:
      - PolicyName: KmsReadOnly
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - kms:GetKeyRotationStatus
            - kms:ListKeys
            - kms:ListAliases
            Resource: '*'
      - PolicyName: S3ReadOnly
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - s3:GetBucketAcl
            - s3:GetBucketLogging
            - s3:GetBucketPolicy
            Resource: '*'
