AWSTemplateFormatVersion: 2010-09-09
Description: Enable AWS Config Service by StackSet required execution and admin role   
Parameters:
  s3bucketname:
    Type: String
    Description: Name of s3 bucket which created by Master stack.
  ConfigserviceIAMroleARN:
    Type: String
    Description: Enter Config Service IAM Role Arn which created by Master stack. 
  DeliveryFrequency:
    Type: String
    Default: Six_Hours
    Description: The frequency with which AWS Config delivers configuration snapshots.
    AllowedValues:
      - One_Hour
      - Three_Hours
      - Six_Hours
      - Twelve_Hours
      - TwentyFour_Hours
  PrimaryEmailConfigservice:
    Type: String
    AllowedPattern: ".+@.+"
    Default: 'example@example.com'
    Description: "'Optional' Enter the email address you want to notify  stream change and notifications. ' this can cause a high volume of email.'"
Conditions:
    ConfigSubcription: !Not [!Equals [!Ref PrimaryEmailConfigservice, 'example@example.com']]
Resources:
  ConfigTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: configservice-topic
      DisplayName: AWS Config Notification Topic
  ConfigTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref ConfigTopic
      PolicyDocument:
        Statement:
          - Sid: AWSConfigSNSPolicy
            Action:
              - sns:Publish
            Effect: Allow
            Resource: !Ref ConfigTopic
            Principal:
              Service:
                - config.amazonaws.com
  NotifcationSNS:
    Condition: Subcription
    Type: AWS::SNS::Subscription
    Properties:
        Endpoint: !Ref PrimaryEmailConfigservice
        Protocol: email
        TopicArn: !Ref 'ConfigTopic'
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: myconfigservice-recorder
      RoleARN: !Ref ConfigserviceIAMroleARN
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true
  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      Name: myconfigservice-deliverychannel
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: !Ref DeliveryFrequency
      S3BucketName: !Ref s3bucketname
      SnsTopicARN: !Ref ConfigTopic
Outputs:
  SNSTopicname:
    Description: 'Name of SNS created for Cloudtrail events'
    Value: !GetAtt 'ConfigTopic.TopicName'