Parameters:
  GuardDutyfindingPublish:
    Type: String
    Description: Enter the Finding Publish Frequency Value.
    Default: FIFTEEN_MINUTES
    AllowedValues:
      - FIFTEEN_MINUTES
      - ONE_HOUR
      - Six_Hours
  PrimaryEmail:
    Type: String
    AllowedPattern: ".+@.+"
    Default: 'example@example.com'
    Description: "'Optional' Enter the email address you want to notify  GuardDuty findings and events."
Conditions:
    Subcription: !Not [!Equals [!Ref PrimaryEmail, 'example@example.com']]
Resources:
  Detector:
    Properties:
      Enable: 'true'
      FindingPublishingFrequency: !Ref GuardDutyfindingPublish
    Type: 'AWS::GuardDuty::Detector'
  EventsRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: Notify-GuardDuty-Event
      Description: This rule will notify guardduty events and finding to SNS.
      EventPattern:
        source:
          - aws.guardduty
      State: ENABLED
      Targets:
        - Arn: !Ref GaurddutyTopic
          Id: sns
  GaurddutyTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: GuardDuty-findings-Topic
      DisplayName: AWS Guardduty Notification Topic
      Subscription: []
  GuardDutyTopicPolicy:
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'sns:Publish'
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Resource:
              - !Ref GaurddutyTopic
      Topics:
        - !Ref GaurddutyTopic
    Type: 'AWS::SNS::TopicPolicy'
  NotifcationSNS:
    Condition: Subcription
    Type: AWS::SNS::Subscription
    Properties:
        Endpoint: !Ref PrimaryEmail
        Protocol: email
        TopicArn: !Ref 'GaurddutyTopic'